AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # CodeBuild
  BuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: codebuild.amazonaws.com
  S3ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ReadS3Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource:
              - !Join
                - ''
                - - !GetAtt SourceBucket.Arn
                  - "/code_build_handson.zip"
              - !Join
                - ''
                - - !GetAtt SourceBucket.Arn
                  - "/code_build_handson.zip/*"
            Action:
              - "s3:GetObject"
              - "s3:GetObjectVersion"
          - Effect: "Allow"
            Resource:
              - !GetAtt SourceBucket.Arn
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
      Roles:
        - !Ref BuildServiceRole
  BuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BuildPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource:
              - "*"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
          - Effect: "Allow"
            Resource:
              - "*"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
          - Effect: "Allow"
            Resource:
              - !GetAtt Build.Arn
            Action:
              - "codebuild:CreateReportGroup"
              - "codebuild:CreateReport"
              - "codebuild:UpdateReport"
              - "codebuild:BatchPutTestCases"
              - "codebuild:BatchPutCodeCoverages"
      Roles:
        - !Ref BuildServiceRole
  Build:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Name: deploy_cfn_handson
      Source:
        Type: S3
        Location: !Join
          - ''
          - - !Ref SourceBucket
            - "/code_build_handson.zip"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      ServiceRole: !GetAtt BuildServiceRole.Arn
  SourceBucket:
    Type: AWS::S3::Bucket

  # トリガー実行
  TriggerS3PutRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: events.amazonaws.com
  ExecCodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ExecCodeBuildPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource: !GetAtt Build.Arn
            Action:
              - "codebuild:StartBuild"
      Roles:
        - !Ref TriggerS3PutRole
  TriggerS3PutEvents:
    Type: AWS::Events::Rule
    Properties:
      Name: putSource
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - CopyObject
            - CompleteMultiPartUpload
            - PutObject
          requestParameters:
            bucketName:
              - !Ref SourceBucket
            key:
              - "code_build_handson.zip"
      State: ENABLED
      Targets:
        - RoleArn: !GetAtt TriggerS3PutRole.Arn
          Arn: !GetAtt Build.Arn
          Id: "ExecRunDeploy"
  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SourceBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource: !GetAtt SourceBucket.Arn
            Action: "s3:GetBucketAcl"
            Principal:
              Service: "cloudtrail.amazonaws.com"
          - Effect: "Allow"
            Resource: !Join
              - ''
              - - !GetAtt SourceBucket.Arn
                - "/AWSLogs/913647930742/*"
            Action: "s3:PutObject"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Condition:
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"
  TrailS3Put:
    Type: AWS::CloudTrail::Trail
    DependsOn:
      - CloudTrailBucketPolicy
    Properties:
      TrailName: PutSource
      S3BucketName: !Ref SourceBucket
      IsLogging: true
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - "arn:aws:s3:::"
          IncludeManagementEvents: false
          ReadWriteType: All
