AWSTemplateFormatVersion: "2010-09-09"
Resources:
  BuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: codebuild.amazonaws.com
  S3ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ReadS3Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource:
              - !Join
                - ''
                - - !GetAtt SourceBucket.Arn
                  - "/code_build_handson.zip"
              - !Join
                - ''
                - - !GetAtt SourceBucket.Arn
                  - "/code_build_handson.zip/*"
            Action:
              - "s3:GetObject"
              - "s3:GetObjectVersion"
          - Effect: "Allow"
            Resource:
              - !GetAtt SourceBucket.Arn
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
      Roles:
        - !Ref BuildServiceRole
  BuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BuildPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource:
              - "*"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
          - Effect: "Allow"
            Resource:
              - "*"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
          - Effect: "Allow"
            Resource:
              - !GetAtt Build.Arn
            Action:
              - "codebuild:CreateReportGroup"
              - "codebuild:CreateReport"
              - "codebuild:UpdateReport"
              - "codebuild:BatchPutTestCases"
              - "codebuild:BatchPutCodeCoverages"
      Roles:
        - !Ref BuildServiceRole
  Build:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Name: deploy_cfn_handson
      Source:
        Type: S3
        Location: !Join
          - ''
          - - !Ref SourceBucket
            - "/code_build_handson.zip"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      ServiceRole: !GetAtt BuildServiceRole.Arn
  SourceBucket:
    Type: AWS::S3::Bucket
