AWSTemplateFormatVersion: "2010-09-09"
Description:
  "Sample CloudFormation template"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: "VPC領域"

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: "パブリックサブネット"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        !Ref VPC
      InternetGatewayId:
        !Ref InternetGateway

  # RouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId:
  #       !Ref VPC

  # DefaultRoute:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId:
  #       !Ref RouteTable
  #     DestinationCidrBlock: 0.0.0.0/0
  #     GatewayId:
  #       !Ref InternetGateway

  # SubnetRouteTableAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     SubnetId:
  #       !Ref PublicSubnet
  #     RouteTableId:
  #       !Ref RouteTable
